chore(config): Remove calls to quote
deis/monitor pull request #142
Opened 2016-09-20 19:13 UTC by jchauncey

2016-09-20 19:13 UTC, jchauncey commented
This is going to break ci but wanted to get this PR created so I dont forget about it

2016-09-23 17:40 UTC, arschles commented on telegraf/manifests/deis-monitor-telegraf-daemon.yaml
> +            value: "http://$(DEIS_NSQD_SERVICE_HOST):$(DEIS_NSQD_SERVICE_PORT_HTTP)" {{- if env "LOGGER_REDIS_LOCATION" | default .logger_redis_location | ne "off-cluster" }}
you can put the `if` on the next line and the `{{-` will remove that newline. might be easier to read

2016-09-23 17:40 UTC, arschles requested changes

2016-09-23 18:35 UTC, jchauncey commented on telegraf/manifests/deis-monitor-telegraf-daemon.yaml
> +            value: "http://$(DEIS_NSQD_SERVICE_HOST):$(DEIS_NSQD_SERVICE_PORT_HTTP)" {{- if env "LOGGER_REDIS_LOCATION" | default .logger_redis_location | ne "off-cluster" }}
fixed

2016-09-23 18:42 UTC, arschles approved these changes

2016-09-23 18:47 UTC, merged