feat(charts): add optional persistence storage to influxdb and grafana
deis/monitor pull request #169
Opened 2017-01-10 13:22 UTC by rimusz

2017-01-11 18:11 UTC, bacongobbler requested changes

2017-01-11 18:11 UTC, bacongobbler commented on charts/monitor/values.yaml
> +    size: 5Gi
can we please make this configurable?

2017-01-11 18:11 UTC, bacongobbler commented on charts/monitor/values.yaml
> +    size: 20Gi
can we please make this configurable?

2017-01-11 18:12 UTC, bacongobbler commented
If you also wouldn't mind writing some documentation around how one can get this all set up, that would be great. :)

2017-01-11 18:27 UTC, rimusz commented on charts/monitor/values.yaml
> +    size: 20Gi
I think they are configurable enough already, by default it is disabled.

2017-01-11 18:28 UTC, rimusz commented
I was going to write small doc in global `values.yaml` file how to switch persistence on and change other values. Do you want some doc for the website too?

2017-01-11 18:37 UTC, bacongobbler commented
yes please.

2017-01-11 18:38 UTC, rimusz commented
ok, will do the PR for the global `values.yaml` file, first. when all those bits are merged, will work on doc :)

2017-01-11 21:14 UTC, bacongobbler commented on charts/monitor/values.yaml
> +    size: 20Gi
I'm talking about the actual size of the volume claim. Some users may want smaller or bigger voluime claims.

2017-01-12 15:52 UTC, rimusz commented on charts/monitor/values.yaml
> +    size: 20Gi
it is already in `values.yaml` file where user can change. but my idea is put that to global `values.yaml` file too, so enabling persistence you can set the storage size too

2017-01-12 16:14 UTC, bacongobbler commented on charts/monitor/values.yaml
> +    size: 20Gi
sorry! I was clearly misreading it.

2017-01-12 16:15 UTC, bacongobbler approved these changes

2017-01-12 16:23 UTC, rimusz commented
will work on global `values.yaml` file changes then

2017-01-13 18:33 UTC, rimusz commented
tested the changes of running it in my dev Workflow cluster

2017-01-17 03:23 UTC, bacongobbler commented
Closes #93

2017-01-17 03:23 UTC, bacongobbler commented
Closes #92

2017-01-24 20:01 UTC, vdice approved these changes
Tested in combination with https://github.com/deis/workflow/pull/699 (PV/PVCs successfully created; grafana dashboards and influxdb metrics persist through pod destruction, as expected.)

2017-01-24 21:02 UTC, merged