fix(influx, grafana): Add logic around pvc storage class
deis/monitor pull request #181
Opened 2017-03-10 19:21 UTC by jchauncey

Starting with 1.5.* kubernetes does not provision a storage class. This means when using the volume.beta.kubernetes.io/storage-class the underlying persistent volume cannot be provisioned. Instead, we must use the old volume.alpha.kubernetes.io/storage-class which when passed a value will automatically provision the storage class and the underlying pv

2017-03-10 23:04 UTC, vdice approved these changes
Tested the following on GKE:
1. Upgrade to this PR chart (`workflow-v2.12.1-20170310193849-sha.686491d` from the `workflow-pr` repo) from latest Workflow dev chart install, having set up monitoring persistence via [docs](https://deis.com/docs/workflow/managing-workflow/platform-monitoring/) during pre-upgrade install and there were no adverse affects to existing pv,pvc's
2. Fresh install without any creation of standard storage class mentioned in [docs](https://deis.com/docs/workflow/managing-workflow/platform-monitoring/#pvc-dynamic-provisioning) and pv,pvc's were created automatically.

(`--set monitor.influxdb.persistence.enabled=true,monitor.grafana.persistence.enabled=true` for all cases)

@jchauncey my only question is if https://deis.com/docs/workflow/managing-workflow/platform-monitoring/#pvc-dynamic-provisioning can now be removed?  It doesn't seem needed per scenario 2 mentioned above.

2017-03-14 16:49 UTC, mboersma requested changes

2017-03-14 16:49 UTC, mboersma commented on charts/monitor/charts/grafana/templates/monitor-grafana-pvc.yaml
> +        {{- if .Values.persistence.storageClass }}
Could this be dedented two spaces? Sorry, my OCD spidey-sense is triggered by whitespace misalignment.

2017-03-14 16:49 UTC, mboersma commented on charts/monitor/charts/grafana/templates/monitor-grafana-pvc.yaml
> +      volume.alpha.kubernetes.io/storage-class: default
Dedent by two spaces please, so it aligns with other yaml keys.

2017-03-14 16:49 UTC, mboersma commented on charts/monitor/charts/influxdb/templates/monitor-influxdb-pvc.yaml
> +      volume.alpha.kubernetes.io/storage-class: default
I am a broken record: please remove two spaces here so it aligns better. 😄

2017-03-14 16:50 UTC, mboersma requested changes
I have the same question as @vdice: can https://deis.com/docs/workflow/managing-workflow/platform-monitoring/#pvc-dynamic-provisioning be removed from the docs?

2017-03-14 16:54 UTC, jchauncey commented
@mboersma I was going to do a sweep through the docs once we got the new influx chart in place since that may bring more changes if thats ok with you?

2017-03-14 18:11 UTC, mboersma approved these changes

2017-03-14 18:43 UTC, merged